import { CardData } from "components/Card";

export const store_page_mockup = [
  {
    idx: 1,
    title: "2024 타비 뿡댕이 키링",
    tallent: 7,
    category: 1,
    detailInfo: "",
    price: 15000,
    updateDate: "2024-09-07",
    reviewCount: 5,
    rate: 5,
    images: ["/test_image.png", "/test_image2.webp", "/test_image3.webp"],
  },
  {
    idx: 2,
    title: "2023 칸나 인형",
    tallent: 2,
    category: 3,
    detailInfo: "",
    price: 65000,
    reviewCount: 3,
    updateDate: "2023-12-02",
    rate: 5,
    images: ["/test_image6.webp", "/test_image6.webp", "/test_image6.webp"],
  },
  {
    idx: 3,
    title: "나나 카라비너 머그",
    tallent: 10,
    category: 5,
    detailInfo: "",
    price: 32000,
    reviewCount: 2,
    updateDate: "2024-01-01",
    rate: 5,
    images: ["/test_image8.webp", "/test_image8.webp", "/test_image8.webp"],
  },
  {
    idx: 4,
    title: "2024 리제 피엔나 다리 쿠션",
    tallent: 6,
    category: 3,
    detailInfo: "",
    price: 45000,
    reviewCount: 1,
    updateDate: "2024-10-01",
    rate: 5,
    images: ["/test_image9.webp", "/test_image9.webp", "/test_image9.webp"],
  },
  {
    idx: 5,
    title: "스텔라이브 아티산 키캡 - 아카네 리제",
    tallent: 6,
    category: 2,
    detailInfo: "",
    price: 65000,
    updateDate: "2024-11-27",
    rate: 5,
    reviewCount: 5,
    images: ["/test_image2.webp", "/test_image2.webp", "/test_image2.webp"],
  },
  {
    idx: 6,
    title: "스텔라이브 아티산 키캡 - 네네코 마시로",
    tallent: 5,
    category: 2,
    detailInfo: "",
    price: 65000,
    updateDate: "2024-11-27",
    rate: 5,
    reviewCount: 4,
    images: ["/test_image3.webp", "/test_image3.webp", "/test_image3.webp"],
  },
  {
    idx: 7,
    title: "스텔라이브 아티산 키캡 - 아라하시 타비",
    tallent: 7,
    category: 2,
    detailInfo: "",
    price: 65000,
    updateDate: "2024-11-27",
    rate: 5,
    reviewCount: 3,
    images: ["/test_image4.webp", "/test_image4.webp", "/test_image4.webp"],
  },
  {
    idx: 8,
    title: "스텔라이브 아티산 키캡 - 시라유키 히나",
    tallent: 4,
    category: 2,
    detailInfo: "",
    price: 65000,
    updateDate: "2024-11-27",
    rate: 5,
    reviewCount: 2,
    images: ["/test_image5.webp", "/test_image5.webp", "/test_image5.webp"],
  },
  {
    idx: 9,
    title: "스텔라이브 아티산 키캡 - 아야츠노 유니",
    tallent: 3,
    category: 2,
    detailInfo: "",
    price: 65000,
    updateDate: "2024-11-27",
    rate: 5,
    reviewCount: 1,
    images: ["/test_image10.webp", "/test_image10.webp", "/test_image10.webp"],
  },
  {
    idx: 10,
    title: "스텔라이브 아티산 키캡 - 아이리 칸나",
    tallent: 2,
    category: 2,
    detailInfo: "",
    price: 65000,
    updateDate: "2024-11-27",
    rate: 5,
    reviewCount: 5,
    images: ["/test_image11.webp", "/test_image11.webp", "/test_image11.webp"],
  },
  {
    idx: 11,
    title: "스텔라이브 아티산 키캡 거치대 - 구름 트레이",
    tallent: 0,
    category: 1,
    detailInfo: "",
    price: 65000,
    updateDate: "2024-11-27",
    rate: 5,
    reviewCount: 4,
    images: ["/test_image12.webp", "/test_image12.webp", "/test_image12.webp"],
  },
  {
    idx: 12,
    title: "스텔라이브 머그컵",
    tallent: 0,
    category: 5,
    detailInfo: "",
    price: 12000,
    updateDate: "2023-06-26",
    rate: 5,
    reviewCount: 3,
    images: ["/test_image13.png", "/test_image13.png", "/test_image13.png"],
  },
  {
    idx: 13,
    title: "2023 타비 아크릴 키링",
    tallent: 7,
    category: 1,
    detailInfo: "",
    price: 9000,
    updateDate: "2023-09-07",
    rate: 5,
    reviewCount: 2,
    images: ["/test_image14.png", "/test_image14.png", "/test_image14.png"],
  },
  {
    idx: 14,
    title: "2023 타비 홈 뿡리퍼",
    tallent: 7,
    category: 6,
    detailInfo: "",
    price: 38000,
    updateDate: "2023-09-07",
    rate: 5,
    reviewCount: 1,
    images: ["/test_image15.png", "/test_image15.png", "/test_image15.png"],
  },
  {
    idx: 15,
    title: "2023 리제 연결 아크릴 키링",
    tallent: 6,
    category: 1,
    detailInfo: "",
    price: 15000,
    updateDate: "2024-10-01",
    rate: 5,
    reviewCount: 5,
    images: ["/test_image16.png", "/test_image16.png", "/test_image16.png"],
  },
  {
    idx: 16,
    title: "유니 아크릴 키링 Ver.1",
    tallent: 3,
    category: 1,
    detailInfo: "",
    price: 9000,
    updateDate: "2023-05-21",
    rate: 5,
    reviewCount: 4,
    images: ["/test_image17.png", "/test_image17.png", "/test_image17.png"],
  },
  {
    idx: 17,
    title: "유니 아크릴 키링 Ver.2",
    tallent: 3,
    category: 1,
    detailInfo: "",
    price: 9000,
    updateDate: "2023-05-21",
    rate: 5,
    reviewCount: 3,
    images: ["/test_image18.png", "/test_image18.png", "/test_image18.png"],
  },
] as CardData[];
